services:
  python:
    image: mcr.microsoft.com/devcontainers/python:1-3.12-bullseye
    environment:
      - PYTHONUNBUFFERED=${PYTHONUNBUFFERED}
      - MONGO_USER=${MONGO_USER}
      - MONGO_PASSWORD=${MONGO_PASSWORD}
      - MONGO_HOST=${MONGO_HOST}
      - MONGO_PORT=${MONGO_PORT}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - WP_URL=${WP_URL}
      - WP_USER=${WP_USER}
      - WP_PASSWORD=${WP_PASSWORD}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - BING_API_KEY=${BING_API_KEY}
    depends_on:
      - mongodb
    networks:
      - internal_network
    volumes:
      - workspace_data:/workspace  # Use a named volume for the workspace
    command: tail -f /dev/null  # Keeps the container running indefinitely

  mongodb:
    image: mongo:6
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    volumes:
      - mongodb_data:/data/db
    networks:
      - internal_network

  redis:
    image: redis:6
    restart: unless-stopped
    networks:
      - internal_network

volumes:
  mongodb_data:
  workspace_data:  # Named volume for storing the cloned repository

networks:
  internal_network:
    driver: bridge
